app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::auth();
});


Route::group(['middleware' => ['web', 'auth']], function () {
    Route::get('/home', 'HomeController@index');

    Route::resource('profile', 'ProfileController', ['only' => ['index']]);
    Route::resource('account', 'AccountController');
    Route::resource('account.device', 'DeviceController');
});

Route::group(['prefix' => 'api/v1', 'middleware' => ['device.auth']], function () {
    Route::post('trends/decimal', 'Api\V1\TrendWriterController@postDecimal');
});

app/Account.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Account extends Model
{
    protected $fillable = [
        'name', 'expiration', 'device_limit', 'storage_limit',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function devices()
    {
        return $this->hasMany(Device::class);
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Account;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;

class AccountController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    public function create()
    {
        return view( 'accounts.create' );
    }

    public function store(Request $request)
    {
        $user = Auth::user();

        $packages = Config::get('galert.packages');
        $packages = json_decode(json_encode($packages), FALSE);

        $name = $request->input('package');
        $package = $packages->$name;

        $user->accounts()->create([
            'name' => $package->name,
            'expiration' => Carbon::now()->addDays($package->expiration),
            'device_limit' => $package->max_devices,
            'storage_limit' => 0
        ]);

        growl()->success('Account added.');

        return redirect()->route('profile.index');
    }


    public function show(Request $request, $id)
    {
        $user = Auth::user();

        $account = $user->accounts()->findOrfail($id);

        return view( 'accounts.show', [ 'account' => $account ] );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/accounts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add Account</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-4">
                                    <form class="form-horizontal" role="form" method="POST" action="{{ route('account.store') }}">
                                        {!! csrf_field() !!}
                                        <div class="form-group">
                                            <div class="col-md-8 col-md-offset-2">
                                                <input type="hidden" name="package" value="free">
                                                <button type="submit" class="btn btn-primary">
                                                    Free
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-4">
                                    <form class="form-horizontal" role="form" method="POST" action="{{ route('account.store') }}">
                                        {!! csrf_field() !!}
                                        <div class="form-group">
                                            <div class="col-md-8 col-md-offset-2">
                                                <input type="hidden" name="package" value="silver">
                                                <button type="submit" class="btn btn-primary">
                                                    Silver
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                <div class="col-md-4">
                                    <form class="form-horizontal" role="form" method="POST" action="{{ route('account.store') }}">
                                        {!! csrf_field() !!}
                                        <div class="form-group">
                                            <div class="col-md-8 col-md-offset-2">
                                                <input type="hidden" name="package" value="gold">
                                                <button type="submit" class="btn btn-primary">
                                                    Gold
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/accounts/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Account {{ $account->name }} Devices
                        <a class="btn btn-xs btn-primary pull-right" href="{{ route('account.device.create', [$account]) }}">Add</a>
                    </div>
                    <div class="panel-body">
                        <ul class="list-unstyled">
                            @forelse($account->devices as $device)
                                <li>
                                    <a href="{{ route('account.device.show', [$account, $device]) }}">{{ $device->name }}</a> <small>({{$device->timezone}})</small>
                                </li>
                                api-key: <code>{{ $device->api_key }}</code>
                            @empty
                                <li>no devices</li>
                            @endforelse
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection