app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => 'web'], function () {
    Route::auth();
});


Route::group(['middleware' => ['web', 'auth']], function () {
    Route::get('/home', 'HomeController@index');

    Route::resource('profile', 'ProfileController', ['only' => ['index']]);
    Route::resource('account', 'AccountController');
    Route::resource('account.device', 'DeviceController');
});

Route::group(['prefix' => 'api/v1', 'middleware' => ['device.auth']], function () {
    Route::post('trends/decimal', 'Api\V1\TrendWriterController@postDecimal');
});

app/Device.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Device extends Model
{
    protected $fillable = [
        'name', 'timezone'
    ];

    public function account()
    {
        return $this->belongsTo(Account::class);
    }

    public function items()
    {
        return $this->hasMany(TrendItem::class);
    }

    public static function boot()
    {
        parent::boot();

        static::created( function ( $model )
        {
            $model->api_key = Device::generateKey();
            $model->save();
        } );
    }

    public static function generateKey()
    {
        $salt = sha1(time() . mt_rand());
        $newKey = substr($salt, 0, 40);

        return $newKey;
    }
}

app/Http/Controllers/DeviceController.php
<?php

namespace App\Http\Controllers;

use App\Account;
use App\Device;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Auth;

class DeviceController extends Controller
{

    public function index()
    {
        //
    }


    public function create(Request $request, $id)
    {
        $user = Auth::user();
        $account = $user->accounts()->findOrfail($id);
        $timezones = $this->timeZoneList();

        return view('devices.create', ['account' => $account, 'timezones' => $timezones]);
    }


    public function store(Request $request, $id)
    {
        $user = Auth::user();
        $account = $user->accounts()->findOrfail($id);

        $name = $request->input('name');
        $tz = $request->input('timezone');

        $account->devices()->create([
            'name' => $name,
            'timezone' => $tz,
            'last_contact' => Carbon::now()
        ]);

        return redirect()->route('account.show', [$account]);
    }

    public function show(Account $account, Device $device)
    {
        $items = [];

        $timezone = $device->timezone;

        $start = Carbon::now( $timezone )->subDays(7)->startOfDay()->setTimezone( 'UTC' );
        $end = Carbon::now( $timezone )->endOfDay()->setTimezone( 'UTC' );

        //$start = Carbon::now()->subDays(5)->startOfDay();
       // $start = Carbon::now()->startOfDay();

        foreach($device->items as $item)
        {
            $values = $item->valuesBetweenDates( $start, $end )->lists('value', 'timestamp');

            $points = [];
            foreach($values as $datetime => $value)
            {
                $data = [Carbon::parse($datetime )->setTimezone( $timezone )->toIso8601String(), $value];
                $points[] = $data;
            }

            $i = [];
            $i['item'] = $item;
            $i['points'] = $points;

            $items[] =$i;
        }

        return view('devices.show', [ 'account' => $account, 'device' => $device, 'items' => $items ]);
    }

    private function timeZoneList()
    {
        $zones_array = [];
        $timestamp   = time();
        foreach ( timezone_identifiers_list() as $key => $zone )
        {
            date_default_timezone_set( $zone );
            $zones_array[ $key ][ 'zone' ]          = $zone;
            $zones_array[ $key ][ 'diff_from_GMT' ] = 'UTC/GMT ' . date( 'P', $timestamp );
        }

        return $zones_array;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/devices/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add Device</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <form class="form-horizontal" role="form" method="POST" action="{{ route('account.device.store', [$account]) }}">
                                    {!! csrf_field() !!}
                                    <div class="form-group">
                                        <div class="col-md-12">
                                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                                <label class="col-md-2 control-label">Name</label>

                                                <div class="col-md-8">
                                                    <input type="text" class="form-control" required="required" name="name" value="{{ old('name') }}">

                                                    @if ($errors->has('name'))
                                                        <span class="help-block">
                                                            <strong>{{ $errors->first('name') }}</strong>
                                                        </span>
                                                    @endif
                                                </div>
                                            </div>
                                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                                <label class="col-md-2 control-label">Timezone</label>

                                                <div class="col-md-8">
                                                    <select name="timezone" class="form-control">
                                                        <?php
                                                        foreach($timezones as $tz)
                                                        {
                                                            $selected = old('time_zone', 'America/Chicago') == $tz['zone'] ? 'selected="selected"' : '';
                                                            echo '<option value="' . $tz['zone'] . '" ' . $selected . '>' . $tz['zone'] . '</option>';
                                                        }
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                            <button type="submit" class="btn btn-primary">
                                                Submit
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/devices/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h2 class="page-header">Device: {{ $device->name }} ({{ $device->items()->count() }})</h2>
        <div class="row">
            @foreach($items as $trend_item)
                <div class="col-md-6">
                    @include('devices.partials._decimal-chart')
                </div>
            @endforeach
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

    <script>

        (function ($) {

            $(document).ready(function () {
                google.charts.load('current', {packages: ['corechart', 'line']});
                google.charts.setOnLoadCallback(drawBasic);
            });

            function drawBasic() {

                $('.line-chart').each(function(){
                    var that = this;

                    var points = $(that).data('points');

                    for(var i = 0; i < points.length; i++) {
                        points[i][0] = new Date(points[i][0]);
                        points[i][1] = parseFloat(points[i][1]);
                    }

                   console.log(points);

                    var data = new google.visualization.DataTable();
                    data.addColumn('datetime', 'X');
                    data.addColumn('number', 'Value');

                    data.addRows(points);

                    var options = {
                        width: '100%',
                        height: 500,
                        legend: {position: 'none'},
                        enableInteractivity: false,
                        chartArea: {
                            width: '85%'
                        },
                        hAxis: {
                            gridlines: {
                                count: -1,
                                units: {
                                    days: {format: ['MMM dd']},
                                    hours: {format: ['HH:mm', 'ha']},
                                }
                            },
                            minorGridlines: {
                                units: {
                                    hours: {format: ['hh:mm:ss a', 'ha']},
                                    minutes: {format: ['HH:mm a Z', ':mm']}
                                }
                            }
                        }
                    };


                    var chart = new google.visualization.LineChart(that);

                    chart.draw(data, options);
                });

            }

        })(jQuery);
    </script>

@endsection